# Generated by Django 5.2 on 2026-01-14 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='balance_wheel',
            field=models.BooleanField(default=False, verbose_name='Только публичные привычки в колесе баланса'),
        ),
        migrations.AddField(
            model_name='user',
            name='notification_habit',
            field=models.BooleanField(default=True, verbose_name='Напоминание о привычках'),
        ),
        migrations.AddField(
            model_name='user',
            name='notification_quests',
            field=models.BooleanField(default=True, verbose_name='Уведомление о квестах'),
        ),
        migrations.AddField(
            model_name='user',
            name='notification_streak',
            field=models.BooleanField(default=True, verbose_name='Уведомление о страйке'),
        ),
        migrations.AddField(
            model_name='user',
            name='participation_in_ratings',
            field=models.BooleanField(default=True, verbose_name='Участие в рейтингах'),
        ),
    ]
