# Generated by Django 5.2 on 2026-01-14 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_user_balance_wheel_user_notification_habit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='level',
            field=models.BigIntegerField(default=1, verbose_name='Уровень'),
        ),
        migrations.AddField(
            model_name='user',
            name='xp',
            field=models.BigIntegerField(default=0, verbose_name='Опыт'),
        ),
    ]
