# Generated by Django 5.2 on 2026-01-14 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_user_level_user_xp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Цена')),
                ('currency', models.CharField(default='RUB', max_length=8, verbose_name='Валюта')),
                ('image_url', models.URLField(blank=True, max_length=750, null=True, verbose_name='URL изображения')),
                ('duration_days', models.PositiveIntegerField(default=0, verbose_name='Длительность (дни)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Доступен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
            ],
        ),
    ]
