# Generated by Django 5.2 on 2026-07-15 18:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_habitcompletion_xp_awarded'),
    ]

    operations = [
        migrations.CreateModel(
            name='HabitTitlePeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название в периоде')),
                ('start_date', models.DateField(verbose_name='Первый день')),
                ('end_date', models.DateField(verbose_name='Последний день')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('habit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='title_periods', to='api.habit')),
            ],
            options={
                'verbose_name': 'Период названия привычки',
                'verbose_name_plural': 'Периоды названий привычек',
                'ordering': ('habit_id', 'start_date', 'id'),
                'indexes': [models.Index(fields=['habit', 'start_date'], name='api_habitti_habit_i_17efd7_idx')],
            },
        ),
    ]
